app_name = "payments_processor"
app_title = "Payments Processor"
app_publisher = "Resilient Tech"
app_description = "Automates the creation of Payment Entries and handles payments."
app_email = "info@resilient.tech"
app_license = "GNU General Public License (v3)"
